Properties object was not being passed in to initialize the BigdataSail instance of the BigdataGraphFixture.  This was noticed when running CI on EC2 EBS was causing OverlappingFileLock exceptions in TestSSSP.  It is my expectation that Amazon EBS behaves poorly when re-openning channels.  We might need to try using instance store for running CI (and HA).
com.bigdata.rdf.graph.impl.bd.TestSSSP.testSSSP (from com.bigdata.rdf.TestAll)
java.lang.RuntimeException: FileLock Overlap
	at com.bigdata.journal.FileMetadata.reopenChannel(FileMetadata.java:1245)
	at com.bigdata.journal.FileMetadata.access$000(FileMetadata.java:58)
	at com.bigdata.journal.FileMetadata$1.reopenChannel(FileMetadata.java:1163)
	at com.bigdata.journal.FileMetadata$1.reopenChannel(FileMetadata.java:1153)
	at com.bigdata.journal.FileMetadata.<init>(FileMetadata.java:946)
	at com.bigdata.journal.FileMetadata.createInstance(FileMetadata.java:1470)
	at com.bigdata.journal.AbstractJournal.<init>(AbstractJournal.java:1140)
	at com.bigdata.journal.Journal.<init>(Journal.java:217)
	at com.bigdata.journal.Journal.<init>(Journal.java:210)
	at com.bigdata.rdf.sail.BigdataSail.createLTS(BigdataSail.java:651)
	at com.bigdata.rdf.sail.BigdataSail.<init>(BigdataSail.java:630)
	at com.bigdata.rdf.sail.BigdataSail.<init>(BigdataSail.java:618)
	at com.bigdata.rdf.graph.impl.bd.BigdataGraphFixture.<init>(BigdataGraphFixture.java:20)
	at com.bigdata.rdf.graph.impl.bd.AbstractBigdataGraphTestCase$1.newGraphFixture(AbstractBigdataGraphTestCase.java:61)
	at com.bigdata.rdf.graph.AbstractGraphTestCase.setUp(AbstractGraphTestCase.java:74)
Caused by: java.nio.channels.OverlappingFileLockException
	at sun.nio.ch.FileChannelImpl$SharedFileLockTable.checkList(FileChannelImpl.java:1166)
	at sun.nio.ch.FileChannelImpl$SharedFileLockTable.add(FileChannelImpl.java:1068)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:868)
	at com.bigdata.journal.FileMetadata.reopenChannel(FileMetadata.java:1210)

Added alternative constructor to allow reuse of an existing AbstractTripleStore.

git-svn-id: svn+ssh://svn.code.sf.net/p/bigdata/code/branches/BIGDATA_RELEASE_1_3_0@7518 8f7bc0f5-282e-0410-95e3-8d296e9bb460