Modified to ONLY run in the SIDS mode pending fix by MP.
{{{
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: context bound, but not quads or sids: < TermId(7B), TermId(5U), com.bigdata.rdf.internal.impl.literal.LiteralExtensionIV@25889b2f, TermId(8B) : Explicit >
	at com.bigdata.rdf.spo.SPORelation.insert(SPORelation.java:2234)
	at com.bigdata.rdf.store.AbstractTripleStore.addStatements(AbstractTripleStore.java:3931)
	at com.bigdata.rdf.rio.StatementBuffer.writeSPOs(StatementBuffer.java:1113)
	at com.bigdata.rdf.rio.StatementBuffer.addStatements(StatementBuffer.java:977)
	at com.bigdata.rdf.rio.StatementBuffer.incrementalWrite(StatementBuffer.java:800)
	at com.bigdata.rdf.rio.StatementBuffer.flush(StatementBuffer.java:400)
	at com.bigdata.rdf.rio.TestStatementBuffer.test_reificationDoneRight_enabled(TestStatementBuffer.java:523)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: context bound, but not quads or sids: < TermId(7B), TermId(5U), com.bigdata.rdf.internal.impl.literal.LiteralExtensionIV@25889b2f, TermId(8B) : Explicit >
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)
	at java.util.concurrent.FutureTask.get(FutureTask.java:83)
	at com.bigdata.rdf.spo.SPORelation.logFuture(SPORelation.java:2260)
	at com.bigdata.rdf.spo.SPORelation.insert(SPORelation.java:2215)
Caused by: java.lang.IllegalArgumentException: context bound, but not quads or sids: < TermId(7B), TermId(5U), com.bigdata.rdf.internal.impl.literal.LiteralExtensionIV@25889b2f, TermId(8B) : Explicit >
	at com.bigdata.rdf.spo.SPOIndexWriter.call(SPOIndexWriter.java:275)
	at com.bigdata.rdf.spo.SPOIndexWriter.call(SPOIndexWriter.java:68)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
}}}

See #526.

git-svn-id: svn+ssh://svn.code.sf.net/p/bigdata/code/branches/BIGDATA_RELEASE_1_3_0@7629 8f7bc0f5-282e-0410-95e3-8d296e9bb460