A bit of a refactor to MappedRDFFileLoadTask to await conditions in loops and to make the Lock and Condition fields final since the javadoc indicates that they are deserialized with no waiters, which is what we want.
This is a bug fix for a problem where the lock was null when close() was invoked.  Since the client had already performed significant processing, I assume that the problem was the lock field was not marked as volatile.  This change makes it final, which should do the trick.

ERROR: 11393670    com.bigdata.service.jini.JiniFederation.executorService3 com.bigdata.service.ndx.pipeline.AbstractMasterTask.call(AbstractMasterTask.java:530): Cancelling: job=com.bigdata.service.jini.master.MappedTaskMaster$1{jobName=music-load, open=false}, cause=java.lang.RuntimeException: java.lang.RuntimeException: com.bigdata.service.jini.master.ResourceBufferSubtask{locator=com.bigdata.service.jini.master.ClientLocator@0, open=false}
java.lang.RuntimeException: java.lang.RuntimeException: com.bigdata.service.jini.master.ResourceBufferSubtask{locator=com.bigdata.service.jini.master.ClientLocator@0, open=false}
        at com.bigdata.util.concurrent.AbstractHaltableProcess.halted(AbstractHaltableProcess.java:82)
        at com.bigdata.service.ndx.pipeline.AbstractMasterTask.awaitAll(AbstractMasterTask.java:641)
        at com.bigdata.service.ndx.pipeline.AbstractMasterTask.call(AbstractMasterTask.java:526)
        at com.bigdata.service.ndx.pipeline.AbstractMasterTask.call(AbstractMasterTask.java:180)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
        at java.util.concurrent.FutureTask.run(FutureTask.java:138)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
        at java.lang.Thread.run(Thread.java:619)
Caused by: java.lang.RuntimeException: com.bigdata.service.jini.master.ResourceBufferSubtask{locator=com.bigdata.service.jini.master.ClientLocator@0, open=false}
        at com.bigdata.service.ndx.pipeline.AbstractSubtask.call(AbstractSubtask.java:239)
        at com.bigdata.service.ndx.pipeline.AbstractSubtask.call(AbstractSubtask.java:66)
        ... 5 more
Caused by: java.lang.IllegalStateException
        at com.bigdata.rdf.load.MappedRDFFileLoadTask.awaitReady(MappedRDFFileLoadTask.java:311)
        at com.bigdata.rdf.load.MappedRDFFileLoadTask.close(MappedRDFFileLoadTask.java:377)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at net.jini.jeri.BasicInvocationDispatcher.invoke(BasicInvocationDispatcher.java:1126)
        at net.jini.jeri.BasicInvocationDispatcher.dispatch(BasicInvocationDispatcher.java:608)
        at com.sun.jini.jeri.internal.runtime.ObjectTable$6.run(ObjectTable.java:597)
        at net.jini.export.ServerContext.doWithServerContext(ServerContext.java:103)
        at com.sun.jini.jeri.internal.runtime.ObjectTable$Target.dispatch0(ObjectTable.java:595)
        at com.sun.jini.jeri.internal.runtime.ObjectTable$Target.access$700(ObjectTable.java:212)
        at com.sun.jini.jeri.internal.runtime.ObjectTable$5.run(ObjectTable.java:568)
        at java.security.AccessController.$$YJP$$doPrivileged(Native Method)
        at java.security.AccessController.doPrivileged(AccessController.java)
        at com.sun.jini.jeri.internal.runtime.ObjectTable$Target.dispatch(ObjectTable.java:565)
        at com.sun.jini.jeri.internal.runtime.ObjectTable$Target.dispatch(ObjectTable.java:540)
        at com.sun.jini.jeri.internal.runtime.ObjectTable$RD.dispatch(ObjectTable.java:778)
        at net.jini.jeri.connection.ServerConnectionManager$Dispatcher.dispatch(ServerConnectionManager.java:148)
        at com.sun.jini.jeri.internal.mux.MuxServer$2.run(MuxServer.java:244)
        at java.security.AccessController.$$YJP$$doPrivileged(Native Method)
        at java.security.AccessController.doPrivileged(AccessController.java)
        at com.sun.jini.jeri.internal.mux.MuxServer$1.run(MuxServer.java:241)
        at com.sun.jini.thread.ThreadPool$Worker.run(ThreadPool.java:136)
        at java.lang.Thread.run(Thread.java:619)
        at com.sun.jini.jeri.internal.runtime.Util.__________EXCEPTION_RECEIVED_FROM_SERVER__________(Util.java:108)
        at com.sun.jini.jeri.internal.runtime.Util.exceptionReceivedFromServer(Util.java:101)
        at net.jini.jeri.BasicInvocationHandler.unmarshalThrow(BasicInvocationHandler.java:1303)
        at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:832)
        at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659)
        at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528)
        at $Proxy11.close(Unknown Source)
        at com.bigdata.service.ndx.pipeline.AbstractPendingSetSubtask.awaitPending(AbstractPendingSetSubtask.java:127)
        at com.bigdata.service.ndx.pipeline.AbstractSubtask.call(AbstractSubtask.java:207)
        ... 6 more


git-svn-id: svn+ssh://svn.code.sf.net/p/bigdata/code/trunk@3056 8f7bc0f5-282e-0410-95e3-8d296e9bb460