Working through the resynchronization protocol for HA.
 - done. Not pruning lastCommitTimes for which no votes exist in a
   timely fashion.  These lastCommitTimes are durable znodes with
   ephemeral children. As such, application logic is required in order
   to remove the lastCommitTimes for which no votes remain.  When all
   services are suddenly terminated, the lastCommitTime znodes can not
   be cleared by application logic.  In order to amerliorate this
   issue, I modified to sort the lastCommitTime votes in
   withdrawVote() in order to provide a more stable behavior.  Since
   the votes are now processed in lastCommitTime order, the next time
   a service withdraws its current vote, it should clear out any votes
   for earlier lastCommitTimes that have no remaining votes.

 - done. add sequenceCount to the root block. this will help us know
   how many messages are in an HALog file.

 - done. the resynchronization messages and write cache blocks are now
   being transmitted over the existing write pipeline.  The messages
   currently originate with the leader and must originate with a
   service that is upstream of the service that requests the replay of
   the HALog for a given commit point.  The IHALogRequest message is
   now passed with the IHAWriteMessage.  When non-null, it indicates
   the replay of a historical IHAWriteMessage and the associated
   WriteCache block.  Various code paths were made conditional on
   whether or not the IHALogRequest is non-null.  For example, you can
   not do asserts on the quorum token in a historical message and you
   do not want to truncate the store when passing an historical
   message along to the next service in the write pipeline.

   Note: By deliberate design, the replay of IHAWriteMessages and the
   associated WriteCache buffers will be observed by all services in
   the write pipeline.  While this does mean that services may have to
   forward buffers that they would not have otherwise observed, it
   provides a simple and reliable pattern for moving the data. We can
   leverage that pattern to provide things like off site replication
   (by introducing a proxy service that becomes a pipeline member and
   then stores and forwards the IHAWriteMessages and WriteCache
   blocks).

 - I have made the HA_LOG_DIR option for the HAJournal optional and
   given it a default value.

----

Updated the HAJournal sample deployment files:

- HAJournal.env now specifies a java logging file and JAVAOPTS that will be used by HAJournalServer.sh

- HAJournalServer.sh was modified to use those options.

- README was updated to clarify some aspects of service setup and configuration.

- log4j.properties and logging.properties were modified to log on files.

Note: TEST FIRST.  The shellScript may not work once committed from
OSX.  Verify the logging setups.

----

Bug fix to performance counter reporting to avoid problem with
AssertionError when reporting performance counters with a concurrent
service shutdown.  The access to the live index counters was lifted
into the AbstractJournal which has direct access to the _name2Addr
reference and then exposed to the Journal through a protected method.
The live index counters will now be omitted if there is a concurrent
shutdown.

java.lang.AssertionError
        at com.bigdata.journal.AbstractJournal._getName2Addr(AbstractJournal.java:500)
        at com.bigdata.journal.Journal.getCounters(Journal.java:974)
        at com.bigdata.counters.ganglia.QueryEngineMetricsCollector.collect(QueryEngineMetricsCollector.java:92)
        at com.bigdata.ganglia.GangliaService.gatherMetrics(GangliaService.java:1108)
        at com.bigdata.ganglia.GangliaService$GatherMetricsTask.run(GangliaService.java:1066)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:165)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
----

Bug fix to problem that we just addressed in ZkQuorumImpl.  The
problem has two sides.

(A) The code in getLastValidTokenState() can not reliably clear the
    old token because the watcher has not yet developed a complete
    view of the quorum state.

(B) If the old token is not cleared, then we can not set the new token
    when the quorum meets.  At this point we do have enough state to
    know that the quorum is meeting, but it is possible that another
    service has already observed this.

I think that what we need to do is reliably clear the old token once
we have a coherent picture of the quorum state, or at least once we
have observed that we do not have enough joined services to justify a
met quorum.

I have modified the ZkQuorumImpl code in setupWatchers() to use
synchronous processing when pushing mock events through the code to
build up the initial model of the quorum state.  We can not use
synchronous handling when the events originate in zookeeper (no
blocking operations in the event thread), but this is Ok with the mock
events.  Since these mock events are now handled synchronously, we
know that we have a valid reflection of the quorum by the end of that
method.  At that point, we can conditionally clear the token if
necessary.

I also modified QuorumTokenStateWatcher (in ZkQuorumImpl) to call
through to setToken() if either the lastValidToken and/or the token
differs and QuorumWatcherBase.setToken() to only return immediately if
BOTH the lastValidToken and the token are equal to the newToken.

This appears to fix the issue.  The stack trace that these changes
were made to handle is below:

{{{
ERROR: 13216 2012-10-09 12:50:57,940      WatcherActionService1 com.bigdata.quorum.AbstractQuorum$QuorumWatcherBase$1.run(AbstractQuorum.java:2050): com.bigdata.quorum.QuorumException: The quorum token has not been cleared
com.bigdata.quorum.QuorumException: The quorum token has not been cleared
	at com.bigdata.quorum.zk.ZKQuorumImpl$ZkQuorumActor.doSetToken(ZKQuorumImpl.java:1013)
	at com.bigdata.quorum.AbstractQuorum$QuorumActorBase.conditionalSetToken(AbstractQuorum.java:1735)
	at com.bigdata.quorum.AbstractQuorum$QuorumActorBase.setToken(AbstractQuorum.java:1423)
	at com.bigdata.quorum.AbstractQuorum$QuorumWatcherBase$6.run(AbstractQuorum.java:2837)
	at com.bigdata.quorum.AbstractQuorum$QuorumWatcherBase$1.run(AbstractQuorum.java:2048)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
}}}

We need to add test coverage for the case when the 2 services meet in
a quorum before the third quorum starts.  This is the condition under
which these failure modes can be observed.  The current set of HA3
unit tests for the Quorum logic always start all three quorums at the
same time.


@see https://sourceforge.net/apps/trac/bigdata/ticket/530 (Journal HA)

git-svn-id: svn+ssh://svn.code.sf.net/p/bigdata/code/branches/BIGDATA_RELEASE_1_2_0@6668 8f7bc0f5-282e-0410-95e3-8d296e9bb460