Modified httpd for counters to use 60 cache-control header.
Added a discount factor for the minimum #of index entries and split point in order to aggressively drive index partition splits for new and young scale-out indices so that more of the cluster resources can be brought to bear on the index.

Done. This is a failure to synchronize on the live commitRecordIndex and/or a failure to use a read-only view of the commitRecordIndex instead of the live view.

      ERROR: 1478308    DataServer/logicalService0000000009/b8ecfc73-f6a9-43c8-a921-762380ecc8cb-overflowService1       com.bigdata.resources.PostProcessOldJournalTask.purgeOldResources(PostProcessOldJournalTask.java:2089): Prob      lem purging old resources?
java.lang.NullPointerException
        at com.bigdata.btree.AbstractNode.copyKey(AbstractNode.java:884)
        at com.bigdata.btree.AbstractTuple.copy(AbstractTuple.java:360)
        at com.bigdata.btree.LeafTupleIterator.next(LeafTupleIterator.java:215)
        at com.bigdata.btree.LeafTupleIterator.next(LeafTupleIterator.java:39)
        at cutthecrap.utils.striterators.Expanderator.next(Expanderator.java:71)
        at cutthecrap.utils.striterators.Striterator.next(Striterator.java:60)
        at com.bigdata.btree.AbstractNode$PostOrderEntryIterator.next(AbstractNode.java:686)
        at com.bigdata.resources.StoreManager.getResourcesForTimestamp(StoreManager.java:3695)
        at com.bigdata.resources.StoreManager.purgeOldResources(StoreManager.java:2971)
        at com.bigdata.resources.StoreManager.purgeOldResources(StoreManager.java:3934)
        at com.bigdata.resources.PostProcessOldJournalTask.purgeOldResources(PostProcessOldJournalTask.java:      2079)
        at com.bigdata.resources.PostProcessOldJournalTask.call(PostProcessOldJournalTask.java:1837)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:636)


git-svn-id: svn+ssh://svn.code.sf.net/p/bigdata/code/trunk@1280 8f7bc0f5-282e-0410-95e3-8d296e9bb460