Disabling HALog compression.  It is causing failures for me locally.  Stack trace is below.
{{{
ERROR: 19737 2013-06-03 10:03:19,871      com.bigdata.rwstore.RWStore$11 com.bigdata.io.writecache.WriteCacheService$WriteTask.call(WriteCacheService.java:953): java.lang.AssertionError: b.capacity=6254, checksumBuffer.capacity=1048576
java.lang.AssertionError: b.capacity=6254, checksumBuffer.capacity=1048576
at com.bigdata.io.writecache.WriteCache.getWholeBufferChecksum(WriteCache.java:803)
at com.bigdata.io.writecache.WriteCache.newHAPackage(WriteCache.java:1651)
at com.bigdata.io.writecache.WriteCacheService$WriteTask.writeCacheBlock(WriteCacheService.java:1403)
at com.bigdata.io.writecache.WriteCacheService$WriteTask.doRun(WriteCacheService.java:1031)
at com.bigdata.io.writecache.WriteCacheService$WriteTask.call(WriteCacheService.java:900)
at com.bigdata.io.writecache.WriteCacheService$WriteTask.call(WriteCacheService.java:1)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
at java.util.concurrent.FutureTask.run(FutureTask.java:166)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
at java.lang.Thread.run(Thread.java:722)
ERROR: 19737 2013-06-03 10:03:19,871      com.bigdata.journal.jini.ha.HAJournal.executorService1 com.bigdata.rdf.store.AbstractTripleStore.create(AbstractTripleStore.java:1719): java.lang.RuntimeException: java.lang.AssertionError: b.capacity=6254, checksumBuffer.capacity=1048576: lastRootBlock=rootBlock{ rootBlock=0, challisField=0, version=3, nextOffset=0, localTime=1370278981364 [Monday, June 3, 2013 10:03:01 AM PDT], firstCommitTime=0, lastCommitTime=0, commitCounter=0, commitRecordAddr={off=NATIVE:0,len=0}, commitRecordIndexAddr={off=NATIVE:0,len=0}, blockSequence=0, quorumToken=-1, metaBitsAddr=0, metaStartAddr=0, storeType=RW, uuid=61bb4399-69b7-49f4-b354-ed8bac09b2d0, offsetBits=42, checksum=23665086, createTime=1370278981358 [Monday, June 3, 2013 10:03:01 AM PDT], closeTime=0}
java.lang.RuntimeException: java.lang.AssertionError: b.capacity=6254, checksumBuffer.capacity=1048576: lastRootBlock=rootBlock{  rootBlock=0, challisField=0, version=3, nextOffset=0, localTime=1370278981364 [Monday, June 3, 2013 10:03:01 AM PDT], firstCommitTime=0, lastCommitTime=0, commitCounter=0, commitRecordAddr={off=NATIVE:0,len=0}, commitRecordIndexAddr={off=NATIVE:0,len=0}, blockSequence=0, quorumToken=-1, metaBitsAddr=0, metaStartAddr=0, storeType=RW, uuid=61bb4399-69b7-49f4-b354-ed8bac09b2d0, offsetBits=42, checksum=23665086, createTime=1370278981358 [Monday, June 3, 2013 10:03:01 AM PDT], closeTime=0}
at com.bigdata.journal.AbstractJournal.commit(AbstractJournal.java:2981)
at com.bigdata.rdf.store.LocalTripleStore.commit(LocalTripleStore.java:80)
at com.bigdata.rdf.store.AbstractTripleStore.create(AbstractTripleStore.java:1699)
at com.bigdata.rdf.sail.BigdataSail.createLTS(BigdataSail.java:746)
at com.bigdata.rdf.sail.CreateKBTask.doRun(CreateKBTask.java:158)
at com.bigdata.rdf.sail.CreateKBTask.call(CreateKBTask.java:71)
at com.bigdata.rdf.sail.CreateKBTask.call(CreateKBTask.java:1)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
at java.util.concurrent.FutureTask.run(FutureTask.java:166)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.RuntimeException: java.lang.AssertionError: b.capacity=6254, checksumBuffer.capacity=1048576
at com.bigdata.io.writecache.WriteCacheService.flush(WriteCacheService.java:2199)
at com.bigdata.io.writecache.WriteCacheService.flush(WriteCacheService.java:2043)
at com.bigdata.rwstore.RWStore.commit(RWStore.java:3099)
at com.bigdata.journal.RWStrategy.commit(RWStrategy.java:448)
at com.bigdata.journal.AbstractJournal.commitNow(AbstractJournal.java:3284)
at com.bigdata.journal.AbstractJournal.commit(AbstractJournal.java:2979)
... 11 more
Caused by: java.lang.AssertionError: b.capacity=6254, checksumBuffer.capacity=1048576
at com.bigdata.io.writecache.WriteCache.getWholeBufferChecksum(WriteCache.java:803)
at com.bigdata.io.writecache.WriteCache.newHAPackage(WriteCache.java:1651)
at com.bigdata.io.writecache.WriteCacheService$WriteTask.writeCacheBlock(WriteCacheService.java:1403)
at com.bigdata.io.writecache.WriteCacheService$WriteTask.doRun(WriteCacheService.java:1031)
at com.bigdata.io.writecache.WriteCacheService$WriteTask.call(WriteCacheService.java:900)
at com.bigdata.io.writecache.WriteCacheService$WriteTask.call(WriteCacheService.java:1)
... 5 more
}}}

git-svn-id: svn+ssh://svn.code.sf.net/p/bigdata/code/branches/READ_CACHE@7189 8f7bc0f5-282e-0410-95e3-8d296e9bb460