- Removed QuorumService.didMeet().  This method was already deprecated and not used.
- AbstractJournal.setQuorumToken().  Further simplified this method. In particular, if the service was not HAReady and the quorum token was unchanged, then this condition does not cause an AssertionError to be thrown.

- AbstractJournal: An issue was identified where a follow was failing to wait on the GatherTask before checking to see if the local release time was consistent with the release time in the PREPARE message.  This could cause the following exception:
{{{
ERROR: 5146164 2013-08-09 14:31:20,395      com.bigdata.rdf.sail.webapp.BigdataRDFContext.queryService15 com.bigdata.ha.QuorumCommitImpl.prepare2Phase(QuorumCommitImpl.java:375): java.util.concurrent.ExecutionException: java.lang.AssertionError: Local service does not agree with consensusReleaseTime: localReleaseTime=1376073078564, expectedReleaseTime=1376073078984, consensusReleaseTime=com.bigdata.ha.msg.HANotifyReleaseTimeResponse@287ca2ca{commitTime=1376073078985,commitCounter=782}
java.util.concurrent.ExecutionException: java.lang.AssertionError: Local service does not agree with consensusReleaseTime: localReleaseTime=1376073078564, expectedReleaseTime=1376073078984, consensusReleaseTime=com.bigdata.ha.msg.HANotifyReleaseTimeResponse@287ca2ca{commitTime=1376073078985,commitCounter=782}
}}}
The fix was to Prepare2Phase.call() to await the Future for the gather task before making this test.

- Journal: log @ error if we force a barrier break.  We still have a problem here where the GATHER is not robust to a service failure.

- SnapshotManager.isReadyToSnapshot(): modified to use IBufferStrategy.getExtent() in order to avoid a lock in the RWStore that could be contended by a commit.

- HAJournalServer: improved logging for runState changes.

- HAJournalServer: SeekConsensus now calls processEvents() after getActor().pipelineAdd() to ensure that the HASendService and/or HAReceiveService are setup.


There are issues where activities are not cancelled / interrupted if their invariants change.  Examples include:

- RESYNC: If the quorum breaks, then RESYNC should terminate.  Likewise, if the HAReceiveService is not setup, RESYNC should terminate.

- SNAPSHOT: Should terminate if quorum breaks or not HAReady (this is implemented though hooking setQuorumToken() in HAJournal)

- sendHALogForWriteSet(): Should terminate if receiver leaves pipeline, if sender is not quorum leader, etc.

- sendStore(): Should terminate if receiver leaves pipeline, if sender is not quorum leader, etc.

There may be other examples of computations that need to be terminated on an abort or a transition from HAReady to NotReady.

See #695.

git-svn-id: svn+ssh://svn.code.sf.net/p/bigdata/code/branches/READ_CACHE2@7282 8f7bc0f5-282e-0410-95e3-8d296e9bb460