Added explicit touch for failure to resolve the query engine proxy on a data service peer.  This error was observed in one of the SPARQL test suites when running against an embedded federation.  I presume that the cause is a concurrent tear down of the test, or perhaps a failure to wait for the query engine to be created when the test is starting.
WARN : 3157507      com.bigdata.journal.Journal.executorService1 com.bigdata.util.concurrent.Haltable.logCause(Haltable.java:418): com.bigdata.util.concurrent.Haltable@71d9e4b7 : isFirstCause=true : java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)
	at java.util.concurrent.FutureTask.get(FutureTask.java:83)
	at com.bigdata.bop.engine.ChunkedRunningQuery$ChunkTask.call(ChunkedRunningQuery.java:1106)
	at com.bigdata.bop.engine.ChunkedRunningQuery$ChunkTaskWrapper.run(ChunkedRunningQuery.java:704)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at com.bigdata.concurrent.FutureTaskMon.run(FutureTaskMon.java:63)
	at com.bigdata.bop.engine.ChunkedRunningQuery$ChunkFutureTask.run(ChunkedRunningQuery.java:617)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:895)
	at com.bigdata.bop.fed.FederatedQueryEngine.getQueryPeer(FederatedQueryEngine.java:568)
	at com.bigdata.bop.fed.FederatedRunningQuery.getQueryPeer(FederatedRunningQuery.java:345)
	at com.bigdata.bop.fed.FederationChunkHandler.sendChunkMessage(FederationChunkHandler.java:378)
	at com.bigdata.bop.fed.FederationChunkHandler.handleChunk(FederationChunkHandler.java:258)
	at com.bigdata.bop.engine.ChunkedRunningQuery$HandleChunkBuffer.outputChunk(ChunkedRunningQuery.java:1285)
	at com.bigdata.bop.engine.ChunkedRunningQuery$HandleChunkBuffer.outputBufferedChunk(ChunkedRunningQuery.java:1316)
	at com.bigdata.bop.engine.ChunkedRunningQuery$HandleChunkBuffer.flush(ChunkedRunningQuery.java:1338)
	at com.bigdata.bop.bset.CopyOp$CopyTask.call(CopyOp.java:200)
	at com.bigdata.bop.bset.CopyOp$CopyTask.call(CopyOp.java:146)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at com.bigdata.bop.engine.ChunkedRunningQuery$ChunkTask.call(ChunkedRunningQuery.java:1105)

git-svn-id: svn+ssh://svn.code.sf.net/p/bigdata/code/branches/TERMS_REFACTOR_BRANCH@5002 8f7bc0f5-282e-0410-95e3-8d296e9bb460