Revert "Fix constant re-initialization"
This reverts commit 3227208f13ad1bd479065a23bd3fffe088fe45e7.

It produces:
java.util.concurrent.ExecutionException: java.lang.RuntimeException:
Value does not belong to this namespace: value="+0000-03-13T00:00:00Z"