I have reviewed and revised the following aspects of the commit and 2-phase commit protocol:
- Journal: cancellation of the Future in the GATHER consensus protocol is no longer logged as an ERROR.  This is just a data race.  

- HAJournalServer: enterErrorState() is now written to be defensive.  Nothing will be thrown out, even if the HAQuorumService is not running (quorum.terminate())).

- HAJournalServer.HAQuorumServer.start()/terminate() now use an AtomicBoolean to guard those methods and to make enterErrorState() a NOP if the HAQuorumService is currently in either of those methods.

- HAJournalServer.logRootBlock() no longer has the isJoinedService boolean.  This method is only called in the 2-phase commit logic and the 2-phase commit is only executed for services that were joined with the met quorum as of the atomic decision point in commitNow().

- commitNow() - refactored to use a CommitState object and pushed down methods for the different things that are being done into that object.  The error handling for the two phase commit logic was simplified to increase understandability.

- The Prepare2Phase and Commit2Phase tasks were simplified.  The core code was pushed down into private inner methods.  This makes it easier to analyze the error handling code paths.

- TestDumpJournal: added coverage of some more conditions looking to replicate an error observed on the HA3 cluster. I was not able to replicate the problem.  It may have been related to allocator recycling or abnormal failure mode on bigdata17 as per this ticket:
{{{
ERROR: 2885231 2013-10-28 16:05:28,194      qtp230584058-49 com.bigdata.rdf.sail.webapp.StatusServlet.doGet(StatusServlet.java:863): java.lang.RuntimeException: java.lang.ClassCastException: com.bigdata.btree.BTree cannot be cast to com.bigdata.journal.Name2Addr
java.lang.RuntimeException: java.lang.ClassCastException: com.bigdata.btree.BTree cannot be cast to com.bigdata.journal.Name2Addr
	at com.bigdata.journal.DumpJournal.dumpNamedIndicesMetadata(DumpJournal.java:726)
	at com.bigdata.journal.DumpJournal.dumpJournal(DumpJournal.java:599)
	at com.bigdata.rdf.sail.webapp.StatusServlet.doGet(StatusServlet.java:485)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:534)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:929)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:864)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
	at org.eclipse.jetty.server.Server.handle(Server.java:352)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1051)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
	at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:508)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:451)
	at java.lang.Thread.run(Thread.java:724)
Caused by: java.lang.ClassCastException: com.bigdata.btree.BTree cannot be cast to com.bigdata.journal.Name2Addr
	at com.bigdata.journal.AbstractJournal.getIndexWithCommitRecord(AbstractJournal.java:4751)
	at com.bigdata.journal.DumpJournal.dumpNamedIndicesMetadata(DumpJournal.java:706)
	... 23 more
}}}

TODO: 

- Review abort2Phase().  For some invocation contexts, this should be restricted to services that were joined with the met quorum and that voted YES for the PREPARE message.

- QuorumCommitImpl: I have reviewed methods, including the cancellation of remote futures and the error paths. modified to use the local executor service to submit RMI requests in parallel and simplified the code paths for interrupt and error handling for RMI requests or for failures to locate the proxy for a service.  However, the new code causes some problems with the HA CI test suite and is being withheld while I investigate those issues in more depth.

I have run threw the HA CI test suite, RWStore test suite, WORM test suite, and TestBigdataSailWithQuads.  All is green.

See #760

git-svn-id: svn+ssh://svn.code.sf.net/p/bigdata/code/branches/BIGDATA_RELEASE_1_3_0@7501 8f7bc0f5-282e-0410-95e3-8d296e9bb460