See [1,2]. Reconciled edits with Martyn, primarily with respect to (a) elision of pipeline change events in QuorumPipelineImpl to resolve a deadlock [2]; and (b) closing a concurrency hole when a service joins with a met quorum after the GATHER and before the PREPARE. {{{ - QuorumPipelineImpl : incorporated changes for event elision. This   provides a fix for <a   href="http://sourceforge.net/apps/trac/bigdata/ticket/681" >   HAJournalServer deadlock: pipelineRemove() and getLeaderId() </a>.   I also fixed whitespace formatting for the indentation in   elideEvents().  This was some odd mixture of tabs and spaces that   was causing indent rendering issues.
- BufferedWrite: Ignored add of unused logger.

- WriteCacheService : did not accept log @ ERROR messages that were
  designated as "REMOVE TRACE".

- HA messages: modified some IHAMessages that did not override
  toString() to provide useful representations in log output.

- IHAAwaitServiceJoinRequest : javadoc and copyright notice.

- IHAWriteMessage : javadoc update for the commit counter semantics.

- HAReceiveService: added readFuture reference into the log message
  for changeDownstream.

- HASendService: incorporated tryno information into channel reopen
  log messages per mgc.

- HAGlue : folded in changes to awaitServiceJoin(), specifically it
  will now return the most recent consensus release time on the
  leader.  This closes a hole when a service joins after the GATHER
  and before the PREPARE.  By using the leader's consensus release
  time, the service will not permit transactions to start against a
  commit point that has been recycled by the leader.

- AbstractJournal: reconciled.

  - commitNow() was reusing the nonJoinedServices definition from the
    GATHER.  I added a JoinedAndNonJoinedServices helper class.
    Distinct instances of this class are now used for the GATHER and
    for the PREPARE/COMMIT.

  - doLocalCommit(): I did not pick up the 2nd half of this
    if/then/else.  Why is it there?

            if ((shouldFlush || true) && doubleSync) {

                _bufferStrategy.force(false/* metadata */);

            } else {
            	if (log.isInfoEnabled())
            		log.info("ALWAYS FORCE TO DISK");
                _bufferStrategy.force(false/* metadata */);
            }

- AbstractHATransactionService: changed updateReleaseTime() method
  into an override of setReleaseTime() which is public (versus
  protected) in order to expose this to the HAJournalServer.

- Journal: 

    - accepted implementation of updateReleaseTime() method from
      AbstractHATransactionService.

    - modified runWithBarrierLock() to log around the critical section
      so we can observe when this section runs and finishes.

- HAJournal: Modified to log @ INFO the request and result for an HA
  digest.  

- HAJournalServer: reconciled all changes.

  - ServiceLeaveTask: Yes, it should use quorum.token(), not
    NO_QUORUM. There is a difference between the quorum token (which
    just reflects zookeeper) and the journal token (which reflects
    zookeeper plus whether or not the local journal is HAReady).
  
                journal.setQuorumToken(getQuorum().token()); // This is correct.

		   - vs -

                journal.setQuorumToken(Quorum.NO_QUORUM); // This is wrong.

- TestHA3JournalServer: reconciled numerous changes.

  - Modified code that was using a sleep to (presumably) wait until
    the current quorum broke to instead just await the next quorum
    meet.

//        Thread.sleep(50); // wait a while for A to shutdown
//
//      final long token2 = quorum.awaitQuorum(awaitQuorumTimeout * 2,
//      TimeUnit.MILLISECONDS);

        // Wait for the next quorum meet on (token+1).
        final long token2 = awaitNextQuorumMeet(token);
    
- AbstractHA3JournalServerTestCase: converted stderr to log @ INFO.

- AbstractHAJournalServerTestCase: accepted log message @ INFO, but
  made it conditional.

Test failures:

- The 4 "overrides" tests need to be revisited. They still fail.

- testQuorumABC_HAStatusUpdatesWithFailovers: The problem appears to
  be that [leader] can not be compared with [serverB] and [serverC]
  using reference testing (==). [leader] has the same data in this
  case as [serverC] (same UUID, same TcpEndpoint).

  junit.framework.AssertionFailedError: Did not elect leader consistent with expectations:
   leader=Proxy[HAGlue,BasicInvocationHandler[BasicObjectEndpoint[b44e72e1-dd5c-4dbc-9640-129bdab11007,TcpEndpoint[192.168.1.135:55983]]]],
  serverB=Proxy[HAGlue,BasicInvocationHandler[BasicObjectEndpoint[073e0614-26a6-49be-83f4-381ce6338306,TcpEndpoint[192.168.1.135:55965]]]],
  serverC=Proxy[HAGlue,BasicInvocationHandler[BasicObjectEndpoint[b44e72e1-dd5c-4dbc-9640-129bdab11007,TcpEndpoint[192.168.1.135:55983]]]]
	at junit.framework.Assert.fail(Assert.java:47)
	at com.bigdata.journal.jini.ha.TestHA3JournalServer.testQuorumABC_HAStatusUpdatesWithFailovers(TestHA3JournalServer.java:2946)

- testStressStartAB_C_MultiTransactionResync_200_5: I have observed a
  failure of this test (after 33 out of 50 trials). A subsequent run
  of 50 trials succeeded.  Good, but not perfect.

  junit.framework.AssertionFailedError: Fail after 33 trials : java.util.concurrent.TimeoutException
	at junit.framework.TestCase2.fail(TestCase2.java:90)
	at com.bigdata.journal.jini.ha.TestHA3JournalServer.testStressStartAB_C_MultiTransactionResync_200_5(TestHA3JournalServer.java:620)

- testStress_RebuildWithPipelineReorganisation: failed on 7th run.

  java.lang.RuntimeException: junit.framework.AssertionFailedError
	at com.bigdata.io.TestCase3.assertCondition(TestCase3.java:250)
	at com.bigdata.journal.jini.ha.AbstractHA3JournalServerTestCase.awaitFullyMetQuorum(AbstractHA3JournalServerTestCase.java:1990)
	at com.bigdata.journal.jini.ha.TestHA3JournalServer.testStartABC_RebuildWithPipelineReorganisation(TestHA3JournalServer.java:1071)
	at com.bigdata.journal.jini.ha.TestHA3JournalServer._testStress_RebuildWithPipelineReorganisation(TestHA3JournalServer.java:1090)
}}}

[1] https://sourceforge.net/apps/trac/bigdata/ticket/530 (Journal HA)
[2] https://sourceforge.net/apps/trac/bigdata/ticket/681  (HAJournalServer deadlock: pipelineRemove() and getLeaderId())

git-svn-id: svn+ssh://svn.code.sf.net/p/bigdata/code/branches/READ_CACHE@7206 8f7bc0f5-282e-0410-95e3-8d296e9bb460