Minor updates for compilation error.
 [javac] /Users/beebs/Documents/systap/github-clean/bigdata/bigdata-rdf/src/java/com/bigdata/rdf/sparql/ast/eval/AST2BOpContext.java:327: error: constructor StaticAnalysisStats in class StaticAnalysisStats cannot be applied to given types;
    [javac]           saStats = new StaticAnalysisStats(null);
    [javac]                     ^
    [javac]   required: no arguments
    [javac]   found: <null>
    [javac]   reason: actual and formal argument lists differ in length
    [javac] /Users/beebs/Documents/systap/github-clean/bigdata/bigdata-rdf/src/java/com/bigdata/rdf/sparql/ast/eval/AST2BOpUtility.java:238: error: constructor StaticAnalysisStats in class StaticAnalysisStats cannot be applied to given types;
    [javac]            new StaticAnalysisStats(astContainer.getQueryParseTime()));
    [javac]            ^
    [javac]   required: no arguments
    [javac]   found: Long
    [javac]   reason: actual and formal argument lists differ in length