This commit addresses several different issues.
Added doRejectedCommit() into BasicHA and override in HAJournal.  This provides the necessary hook to force the HAJournalServer into an Error state if the service fails a commit (specifically, if it votes NO in prepare2Phase).

Significant cleanup around the access methods to the CommitRecordIndex in AbstractJournal.  In particular, AbstractJournal.getCommitRecordIndex() was being used in several unsafe patterns (esp., getRootBlocks(startTime), getRootBlock(startTime)).  In addition, DumpJournal was using this method can now be run with concurrent operations against the journal, making it unsafe.  The only publically exposed method now returns a read-only committed view of the CommitRecordIndex.  StoreManager was modified to support the new version of getCommitRecordIndex() that accepts a readOnly flag.

{{{
CommitRecordIndex getCommitRecordIndex(long addr, boolean readOnly) 
}}}

JournalTransactionService.findNextCommitTime() was modified to use AbstractJournal.getCommitRecordStrictlyGreaterThan(). That method provides appropriate synchronization for the CommitRecordIndex.

Modified commit2Phase() to NOT purge the HALogs unless prepare2Phase voted YES for all services.  This addresses a problem where one service could vote NO but the logs would be purged before the service left the quorum.  The logs are now correctly retained if a service votes NO for prepare. The didAllServicesCommit flag was added to the IHA2PhaseCommitMessage.  This was done in response to problems identified in TestHA3JournalServerOverrides.

HAJournalServer.ErrorTask() was modified to force a service leave.  This was done in response to problems identified in TestHA3JournalServerOverrides.

QuorumCommitImpl.prepare2Phase() now interprets an error attempting to send the PREPARE message to a server as a "NO" vote (as opposed to only errors in processing the PREPARE message on the remote server).

New tests were added to TestHAJournalServerOverride that examine failure modes where (a) a service votes "NO" for PREPARE; and (b) a service throws an exception out of prepare2Phase().

----

I have observed occasional failures in the following stress test.  See [1]. This looks like a failure to resolve the view of the database through the DefaultResourceLocator, thus passing a [null] view into BigdataSailConnection.attach().  It fails every so many runs through that stress test.  I have some question about whether this a new failure or if it has been failing periodically.  
{{{
TestConcurrentCreateKB.test_concurrentKBCreateAndDiscoveryStressTestOnDistinctJournals()
}}}
The change in this commit to the DefaultResourceLocator is unlikely to be responsible since only read-only tx code paths were effected, but the test failure goes through a read-committed request: 
{{{
                conn = getQueryConnection(indexManager, namespace,
                        ITx.READ_COMMITTED);
}}}
The failure trace is:
{{{
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:252)
	at java.util.concurrent.FutureTask.get(FutureTask.java:111)
	at com.bigdata.rdf.sail.TestConcurrentKBCreate.doConcurrentCreateAndDiscoveryTest(TestConcurrentKBCreate.java:312)
	at com.bigdata.rdf.sail.TestConcurrentKBCreate.test_concurrentKBCreateAndDiscovery(TestConcurrentKBCreate.java:172)
	at com.bigdata.rdf.sail.TestConcurrentKBCreate.test_concurrentKBCreateAndDiscoveryStressTestOnDistinctJournals(TestConcurrentKBCreate.java:227)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at junit.framework.TestCase.runTest(TestCase.java:154)
	at junit.framework.TestCase.runBare(TestCase.java:127)
	at junit.framework.TestResult$1.protect(TestResult.java:106)
	at junit.framework.TestResult.runProtected(TestResult.java:124)
	at junit.framework.TestResult.run(TestResult.java:109)
	at junit.framework.TestCase.run(TestCase.java:118)
	at org.eclipse.jdt.internal.junit.runner.junit3.JUnit3TestReference.run(JUnit3TestReference.java:130)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException
	at com.bigdata.rdf.sail.TestConcurrentKBCreate$DiscoveryTask.call(TestConcurrentKBCreate.java:373)
	at com.bigdata.rdf.sail.TestConcurrentKBCreate$DiscoveryTask.call(TestConcurrentKBCreate.java:1)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException
	at com.bigdata.rdf.sail.BigdataSail$BigdataSailReadOnlyConnection.newTx(BigdataSail.java:4119)
	at com.bigdata.rdf.sail.BigdataSail$BigdataSailReadOnlyConnection.<init>(BigdataSail.java:3986)
	at com.bigdata.rdf.sail.BigdataSail._getReadOnlyConnection(BigdataSail.java:1424)
	at com.bigdata.rdf.sail.BigdataSail.getReadOnlyConnection(BigdataSail.java:1399)
	at com.bigdata.rdf.sail.BigdataSailRepository.getReadOnlyConnection(BigdataSailRepository.java:82)
	at com.bigdata.rdf.sail.TestConcurrentKBCreate.getQueryConnection(TestConcurrentKBCreate.java:434)
	at com.bigdata.rdf.sail.TestConcurrentKBCreate.access$0(TestConcurrentKBCreate.java:405)
	at com.bigdata.rdf.sail.TestConcurrentKBCreate$DiscoveryTask.call(TestConcurrentKBCreate.java:358)
	... 6 more
Caused by: java.lang.IllegalArgumentException
	at com.bigdata.rdf.sail.BigdataSail$BigdataSailConnection.attach(BigdataSail.java:1896)
	at com.bigdata.rdf.sail.BigdataSail$BigdataSailReadOnlyConnection.newTx(BigdataSail.java:4109)
	... 13 more
}}}

[1] https://sourceforge.net/apps/trac/bigdata/ticket/617 (Concurrent KB create fails with "No axioms defined?)

The TestRWJournal, journal.TestAll, TestBigdataSailWithQuads, and HA test suites are all 100% green.  

I did observe one zombie for the HA test suite.  However, this was likely related to a previous run in which a bug (never committed) had caused all of that test suite to fail.

See https://sourceforge.net/apps/trac/bigdata/ticket/530 (Journal HA)

git-svn-id: svn+ssh://svn.code.sf.net/p/bigdata/code/branches/READ_CACHE@7142 8f7bc0f5-282e-0410-95e3-8d296e9bb460