Adjusted the lower error bound since a CI failure shows that it can be quite a bit lower than expected (the task failures are random within a distribution).
junit.framework.AssertionFailedError: error rate: expected=0.1, actual=0.01
	at com.bigdata.concurrent.StressTestNonBlockingLockManagerWithTxDag.test_singleResourceLocking_serialized_waitsFor_lowConcurrency5_withTaskDeath(StressTestNonBlockingLockManagerWithTxDag.java:255)

git-svn-id: svn+ssh://svn.code.sf.net/p/bigdata/code/branches/TERMS_REFACTOR_BRANCH@4807 8f7bc0f5-282e-0410-95e3-8d296e9bb460