Fix to the cancel() method.
This replaces the jetty ConcurrentHashSet with a ConcurrentHashMap.
The semantics of toString() for the latter appear to be well-behaved.
Thus, this appears to fix the HA test suite failures which report

````
java.lang.IllegalArgumentException: Invalid UUID string:
 at java.util.UUID.fromString(UUID.java:194)
 at
com.bigdata.rdf.sail.webapp.StatusServlet.doCancelQuery(StatusServlet.ja
va:318)
````