Introduced a distinction between record and stream serializer APIs.
Added a Session concept to a DataService instance.

Modified distributed join tasks to support fan-in GT one.

Modified distributed federation proxies to support (but not use) custom serializers.

Odd RMI error thrown during JDS pipeline U50 for Q9.  It looks like there was an IO error when deserializing the JoinTask's outcome.  This appears to be driven by an OOM arising from a run on a resource constrained platform.  I have modified the code to log more of the errors and an OOM was in fact observed.

See http://osdir.com/ml/java.sun.javaspaces/2005-09/msg00015.html

See http://osdir.com/ml/java.sun.javaspaces/2005-09/msg00029.html

See http://forums.sun.com/thread.jspa?threadID=5284995 (perhaps post there?)

See http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=4868432

See http://osdir.com/ml/java.sun.jini/2004-04/msg00274.html

See http://www.jini.org/wiki/Mailing_Lists, maybe the jini or RMI list
is the right one?  There is also an IRC channel.

Send mail to JINI-USERS@JAVA.SUN.COM.  You may leave the list at any
time by sending a "SIGNOFF JINI-USERS" command to
LISTSERV@JAVA.SUN.COM.  SET JINI-USERS DIGEST.  More information on
LISTSERV commands can be found in the LISTSERV reference card, which
you can retrieve by sending an "INFO REFCARD" command to
LISTSERV@JAVA.SUN.COM.


ERROR: 344422 pool-1-thread-109         com.bigdata.relation.rule.eval.QueryTask.call(QueryTask.java:99): Problem running query: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.rmi.UnmarshalException: exception unmarshalling response; nested exception is:
	java.io.IOException: I/O error reading from mux connection: java.io.EOFException
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.rmi.UnmarshalException: exception unmarshalling response; nested exception is:
	java.io.IOException: I/O error reading from mux connection: java.io.EOFException
	at com.bigdata.relation.rule.eval.AbstractStepTask.runOne(AbstractStepTask.java:333)
	at com.bigdata.relation.rule.eval.QueryTask.runTasks(QueryTask.java:140)
	at com.bigdata.relation.rule.eval.QueryTask.call(QueryTask.java:76)
	at com.bigdata.relation.rule.eval.QueryTask.call(QueryTask.java:1)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:885)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:907)
	at java.lang.Thread.run(Thread.java:619)
Caused by: java.lang.RuntimeException: java.rmi.UnmarshalException: exception unmarshalling response; nested exception is:
	java.io.IOException: I/O error reading from mux connection: java.io.EOFException
	at com.bigdata.service.proxy.ClientFuture.get(ClientFuture.java:69)
	at com.bigdata.relation.rule.eval.pipeline.JoinMasterTask.awaitAll(JoinMasterTask.java:526)
	at com.bigdata.relation.rule.eval.pipeline.JoinMasterTask.call(JoinMasterTask.java:378)
	at com.bigdata.relation.rule.eval.pipeline.JoinMasterTask.call(JoinMasterTask.java:1)
	at com.bigdata.relation.rule.eval.AbstractStepTask.runOne(AbstractStepTask.java:331)
	... 8 more
Caused by: java.rmi.UnmarshalException: exception unmarshalling response; nested exception is:
	java.io.IOException: I/O error reading from mux connection: java.io.EOFException
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:847)
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethod(BasicInvocationHandler.java:659)
	at net.jini.jeri.BasicInvocationHandler.invoke(BasicInvocationHandler.java:528)
	at $Proxy10.get(Unknown Source)
	at com.bigdata.service.proxy.ClientFuture.get(ClientFuture.java:67)
	... 12 more
Caused by: java.io.IOException: I/O error reading from mux connection: java.io.EOFException
	at com.sun.jini.jeri.internal.mux.Session$MuxInputStream.read(Session.java:852)
	at net.jini.jeri.connection.ConnectionManager$Outbound$Input.read(ConnectionManager.java:515)
	at net.jini.jeri.BasicObjectEndpoint.executeCall(BasicObjectEndpoint.java:411)
	at net.jini.jeri.BasicInvocationHandler.invokeRemoteMethodOnce(BasicInvocationHandler.java:806)
	... 16 more
Caused by: java.io.EOFException
	at com.sun.jini.jeri.internal.mux.SocketChannelConnectionIO.handleReadReady(SocketChannelConnectionIO.java:384)
	at com.sun.jini.jeri.internal.mux.SocketChannelConnectionIO.access$200(SocketChannelConnectionIO.java:41)
	at com.sun.jini.jeri.internal.mux.SocketChannelConnectionIO$Handler.handleSelection(SocketChannelConnectionIO.java:464)
	at com.sun.jini.jeri.internal.runtime.SelectionManager$SelectLoop.run(SelectionManager.java:288)
	at com.sun.jini.thread.ThreadPool$Worker.run(ThreadPool.java:136)
	... 1 more


git-svn-id: svn+ssh://svn.code.sf.net/p/bigdata/code/trunk@1060 8f7bc0f5-282e-0410-95e3-8d296e9bb460